server:
  port: 9881
#  context-path: /${spring.application.name}
#restTemplate.getForEntity("http://cloudservice/hello",String.class).getBody();    这样访问时需注释掉context-path

#############################spring配置#############################
spring:
  application:
    name: cloudservice

############################################################

#############################eureka配置#############################
eureka:
  client:
    serviceUrl:
      defaultZone:  http://127.0.0.1:8888/eureka/
    eureka-server-read-timeout-seconds: 180

