server:
  port: 9885
  #context-path: /${spring.application.name}

#############################spring配置#############################
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gayoHe/Config-File.git
          username: gayoHe
          password: hjy5845201314
          search-paths: file






